[colours]
sector_vertical_limits = [140, 65, 65, 65]
ac_not_concerned = [142, 142, 142]
ac_notified = [84, 179, 108]
ac_assumed = [209, 209, 209]
ac_transferred = [169, 202, 119]
ac_redundant = [124, 209, 237]
conflict_group_moon = [75, 221, 75]
conflict_group_losange = [255, 174, 23]
conflict_group_star = [255, 255, 127]
sep_tool= [255, 176, 176]
sep_warning=[255, 255, 0]
stca_warning=[255, 0, 0]
sep_background=[40, 40, 40]
sep_border=[0, 0, 0]
intention_code_vfr=[255, 121, 0]
intention_code_arrival=[237, 168, 255]
intention_code_departure=[114, 216, 250]
intention_code_lfpg_arr_south=[255, 176, 176]
ocl_tooltip=[255, 246, 216]

[ac_symbols]
size = 5
number_of_trails = 8

[sep]
warning_threshold = 9
lookup_time = 30

[menu]
menu_position = 490

[stca]
high_level_sep = 5
low_level_sep = 3
disable_level = 3500
level_reduced_sep = 14500
time_to_extrapolate = 100
altitude_sep = 900
altitude_coarse_filter = 15000
distance_coarse_filter = 70

comment = "LFEE definitions"

[[sector_vertical_limit]]
text = "660\r\n295"
position = ["N050.06.40.282", "E002.30.02.140"]
size = 60
controller_me = "EEN"
controller_others = []
default = true

[[sector_vertical_limit]]
text = "660\r\n295"
position = ["N050.06.40.282", "E002.30.02.140"]
size = 60
controller_me = "EE"
controller_others = []
controller_not_others = ["EEN"]
default = true

[[sector_vertical_limit]]
text = "660\r\n000"
position = ["N048.35.28.573", "E006.17.43.534"]
size = 60
controller_me = "EE"
controller_others = []
controller_not_others = ["EES"]
default = true

[[sector_vertical_limit]]
text = "660\r\n295"
position = ["N048.35.28.573", "E006.17.43.534"]
size = 60
controller_me = "EE"
controller_others = ["EES"]

[[sector_vertical_limit]]
text = "295\r\n145"
position = ["N048.28.15.974", "E006.08.08.593"]
size = 40
controller_me = "EES"
controller_others = []
default = true

[[sector_vertical_limit]]
#comment = "Below FF HP"
text = "195\r\n000"
position = ["N047.16.09.890","E004.50.55.427"]
size = 40
controller_me = "EES"
controller_others=["FF","FFU"]

[[sector_vertical_limit]]
#comment = "Below FF HP"
text = "195\r\n000"
position = ["N047.16.09.890","E004.50.55.427"]
size = 40
controller_me = "EE"
controller_others=["FF","FFU"]

comment = "LFFF definitions"

[[sector_vertical_limit]]
text = "295\r\n000"
position = ["N050.00.28.922", "E002.46.35.408"]
size = 40
controller_me = "FF"
controller_others = ["EE", "EEN"]
controller_not_others = ["FFN"]

[[sector_vertical_limit]]
text = "295\r\n000"
position = ["N050.00.28.922", "E002.46.35.408"]
size = 40
controller_me = "FFN"
controller_others = []
default = true

[[sector_vertical_limit]]
text = "295\r\n000"
position = ["N049.07.00.209", "E000.12.56.868"]
size = 40
controller_me = "FF"
controller_others = ["RR", "RRE"]
controller_not_others = ["FFW","FFN"]

[[sector_vertical_limit]]
# TH RT OT
text = "295\r\n000"
position = ["N048.21.12.214", "E000.34.21.203"]
size = 40
controller_me = "FFW"
controller_others = ["RR","RRE"]

[[sector_vertical_limit]]
# TH RT OT without RR (up to 660)
text = "660\r\n000"
position = ["N048.21.12.214", "E000.34.21.203"]
size = 40
controller_me = "FFW"
controller_not_others = ["RR","RRE"]
default = true

[[sector_vertical_limit]]
# MZQX above TP TB TN
text = "660\r\n295"
position = ["N049.42.40.221", "E000.31.23.168"]
size = 40
controller_me = "FFW"
controller_not_others = ["RR","RRE"]
default = true

[[sector_vertical_limit]]
# MSQX above DGDO without RR
text = "660\r\n295"
position = ["N048.40.23.315", "E002.05.03.982"]
size = 40
controller_me = "FFW"
controller_others = []
controller_not_others = ["FFW","RR","RRE"]
default = true

[[sector_vertical_limit]]
# West Sectors with RR without FFW
text = "295\r\n000"
position = ["N049.03.27.972", "E000.50.27.678"]
size = 40
controller_me = "FFN"
controller_others = ["RR","RRE"]
controller_not_others = ["FFW"]

[[sector_vertical_limit]]
# West Sectors without RR without FFW
text = "660\r\n000"
position = ["N049.03.27.972", "E000.50.27.678"]
size = 40
controller_me = "FFN"
controller_others = []
controller_not_others = ["FFW","RR","RRE"]
default = true

[[sector_vertical_limit]]
# MSQX above DGDO without RR without FFW
text = "660\r\n295"
position = ["N048.40.23.315", "E002.05.03.982"]
size = 40
controller_me = "FFN"
controller_others = []
controller_not_others = ["FFW","RR","RRE"]
default = true

# FFS
[[sector_vertical_limit]]
#comment = "HP Sector"
text = "660\r\n000"
position = ["N047.23.39.901","E003.30.13.568"]
size = 40
controller_me = "FF"
controller_others=["EE","EES","RR","RRE"]
controller_not_others=["FFS"]

[[sector_vertical_limit]]
#comment = "HP Sector"
text = "660\r\n000"
position = ["N047.23.39.901","E003.00.13.568"]
size = 40
controller_me = "FFS"
controller_others=["EE","EES","RR","RRE"]

[[sector_vertical_limit]]
#comment = "HP Sector above LFEE"
text = "660\r\n195"
position = ["N047.16.09.890","E004.50.55.427"]
size = 40
controller_me = "FF"
controller_others=["EE","EES","RR","RRE"]
controller_not_others=["FFS"]

[[sector_vertical_limit]]
#comment = "HP Sector above LFEE"
text = "660\r\n195"
position = ["N047.16.09.890","E004.50.55.427"]
size = 40
controller_me = "FFS"
controller_others=["EE","EES","RR","RRE"]

[[sector_vertical_limit]]
#comment = "DG AO AR Below LFEE"
text = "295\r\n000"
position = ["N048.47.00.320","E003.32.50.502"]
size = 40
controller_me = "FF"
controller_others=["EE","EES","RR","RRE"]
controller_not_others=["FFS"]

[[sector_vertical_limit]]
#comment = "DG AO AR Below LFEE"
text = "295\r\n000"
position = ["N048.47.09.890","E003.32.50.502"]
size = 40
controller_me = "FFS"
controller_others=["EE","EES","RR","RRE"]

[[sector_vertical_limit]]
#comment = "Below BB P Sector"
text = "295\r\n000"
position = ["N047.41.34.328", "E001.58.11.473"]
size = 40
controller_me = "FF"
controller_others=[]
default = true

[[sector_vertical_limit]]
#comment = "Below BB P Sector"
text = "295\r\n000"
position = ["N047.41.34.328", "E001.58.11.473"]
size = 40
controller_me = "FFS"
controller_others=[]
default = true

comment = "LFRR Definition"

[[sector_vertical_limit]]
text = "660\r\n295"
position = ["N049.07.00.209", "E000.12.56.868"]
size = 60
controller_me = "RR"
controller_others = []
controller_not_others = ["RRE"]
default = true

[[sector_vertical_limit]]
text = "660\r\n295"
position = ["N049.07.00.209", "E000.12.56.868"]
size = 60
controller_me = "RRE"
controller_others = []
controller_not_others = ["RRQ"]
default = true

[[sector_vertical_limit]]
text = "355\r\n295"
position = ["N049.07.00.209", "E000.12.56.868"]
size = 60
controller_me = "RRE"
controller_others = ["RRQ"]

[[sector_vertical_limit]]
text = "660\r\n355"
position = ["N049.07.00.209", "E000.12.56.868"]
size = 60
controller_me = "RRQ"
controller_others = ["RR", "RRE"]

[[sector_vertical_limit]]
text = "660\r\n255"
position = ["N046.57.31.690", "W007.06.33.400"]
size = 100
controller_me = "RRS"
controller_others = []
controller_not_others = ["RRA"]
default = true

[[sector_vertical_limit]]
text = "355\r\n255"
position = ["N046.57.31.690", "W007.06.33.400"]
size = 100
controller_me = "RRS"
controller_others = ["RRA"]
controller_not_others = []

[[sector_vertical_limit]]
text = "660\r\n355"
position = ["N046.57.31.690", "W007.06.33.400"]
size = 100
controller_me = "RRA"
controller_others = []
controller_not_others = []
default = true

[[sector_vertical_limit]]
text = "255\r\n000"
position = ["N046.56.01.238", "W006.15.21.829"]
size = 80
controller_me = "RR"
controller_others = ["RRN", "RRE", "RRS"]

[[sector_vertical_limit]]
text = "660\r\n255"
position = ["N049.29.16.597", "W003.59.35.073"]
size = 60
controller_me = "RRV"
controller_others = [] 
default = true

[[sector_vertical_limit]]
text = "660\r\n255"
position = ["N048.43.18.833", "W007.02.13.441"]
size = 80
controller_me = "RRW"
controller_others = []
default = true

[[sector_vertical_limit]]
text = "660\r\n255"
position = ["N049.10.51.488", "W001.49.55.146"]
size = 60
controller_me = "RRJ"
controller_others = [] 
default = true

comment = "others"

[[sector_vertical_limit]]
text = "195\r\n000"
position = ["N049.13.27.656", "E002.36.28.280"]
size = 40
controller_me = "PGA"
controller_others=["PGA"]

[[sector_vertical_limit]]
text = "195\r\n000"
position = ["N045.30.02.514", "E006.31.44.741"]
size = 20
controller_me = "MM"
controller_others=["LSAS", "LSAG"]

#comment = "LFMM definitions"

[[sector_vertical_limit]]
#comment= "Under swiss"
text = "195\r\n000"
position = ["N045.29.54.291", "E006.31.00.885"]
size = 20
controller_me = "MMN"
controller_others=[]
default = true

[[sector_vertical_limit]]
#comment= "MMN when MNU or MUU is connected"
text = "245\r\n000"
position = ["N045.05.25.063", "E003.00.41.035"]
size = 50
controller_me = "MMN"
controller_others=["MNU","MUU"]

[[sector_vertical_limit]]
#comment= "Under swiss"
text = "195\r\n000"
position = ["N045.29.54.291", "E006.31.00.885"]
size = 20
controller_me = "MM"
controller_others=[]
default = true

[[sector_vertical_limit]]
#comment= "MM with MM_EU connected and no one else"
text = "245\r\n000"
position = ["N043.01.11.054", "E006.06.56.045"]
size = 50
controller_me = "MM"
controller_others=["MEU"]
default = true

[[sector_vertical_limit]]
#comment= "MM with MM_N connected and no one else"
text = "660\r\n000"
position = ["N042.55.19.048", "E005.01.15.028"]
size = 50
controller_me = "MM"
controller_others=["MMN"]
default = true

[[sector_vertical_limit]]
#comment= "MM with MM_NU connected and no one else"
text = "245\r\n000"
position = ["N045.20.59.094", "E003.25.19.045"]
size = 50
controller_me = "MM"
controller_others=["MNU"]
default = true

[[sector_vertical_limit]]
#comment= "MM with MM_U connected and no one else"
text = "245\r\n000"
position = ["N043.29.46.085", "E004.38.34.073"]
size = 50
controller_me = "MM"
controller_others=["MUU"]

[[sector_vertical_limit]]
#comment= "MM with MM_E connected and no one else"
text = "660\r\n000"
position = ["N041.32.47.013", "E004.42.08.007"]
size = 50
controller_me = "MM"
controller_others=["MME"]
default = true

[[sector_vertical_limit]]
#comment= "MM with MM_E connected and no one else"
text = "660\r\n000"
position = ["N045.29.39.048", "E003.05.07.021"]
size = 50
controller_me = "MM"
controller_others=["MME"]
default = true

[[sector_vertical_limit]]
#comment= "MME when no one else above connected"
text = "660\r\n000"
position = ["N043.05.28.092", "E006.21.03.092"]
size = 50
controller_me = "MME"
controller_others=[]
default = true

[[sector_vertical_limit]]
#comment= "MME when MM_EU connected"
text = "245\r\n000"
position = ["N043.05.28.092", "E006.21.03.092"]
size = 50
controller_me = "MME"
controller_others=["MEU"]
default = true

[[sector_vertical_limit]]
#comment= "MEU when anyone else connected"
text = "660\r\n245"
position = ["N043.05.28.092", "E006.21.03.092"]
size = 50
controller_me = "MEU"
controller_others=[]
default = true

[[sector_vertical_limit]]
#comment= "NEM when no one else connected"
text = "660\r\n000"
position = ["N043.05.28.092", "E006.21.03.092"]
size = 50
controller_me = "NEM"
controller_others=[]
default = true

[[sector_vertical_limit]]
#comment= "NEM when NE or U connected"
text = "245\r\n000"
position = ["N043.05.28.092", "E006.21.03.092"]
size = 50
controller_me = "NEM"
controller_others=["MEU","MUU"]
default = true

[[sector_vertical_limit]]
#comment= "NEM when MNU connected"
text = "245\r\n000"
position = ["N045.05.25.063", "E003.00.41.035"]
size = 50
controller_me = "NEM"
controller_others=["MNU"]
default = true

[[sector_vertical_limit]]
#comment= "MNU when anyone else connected"
text = "660\r\n245"
position = ["N045.05.25.063", "E003.00.41.035"]
size = 50
controller_me = "MNU"
controller_others=[]
default = true

[[sector_vertical_limit]]
#comment= "MM_U connected"
text = "660\r\n245"
position = ["N042.31.33.017", "E004.53.35.079"]
size = 50
controller_me = "MUU"
controller_others=[]
default = true

#comment = "LFBB definitions"

[[sector_vertical_limit]]
comment= "Above MM T Sector"
text = "660\r\n195"
position = ["N045.45.34.465","E002.55.47.753"]
size = 40
controller_me = "BB"
controller_others = []
default = true

[[sector_vertical_limit]]
#comment= "Above MM T Sector"
text = "660\r\n195"
position = ["N045.45.34.465","E002.55.47.753"]
size = 40
controller_me = "BBN"
controller_others = []
default = true

[[sector_vertical_limit]]
comment= "Above MM H Sector"
text = "660\r\n195"
position = ["N044.02.28.719","E002.50.28.916"]
size = 40
controller_me = "BB"
controller_others = []
default = true

[[sector_vertical_limit]]
#comment= "Above MM H Sector"
text = "660\r\n195"
position = ["N044.02.28.719","E002.50.28.916"]
size = 40
controller_me = "BBS"
controller_others = []
default = true

[[sector_vertical_limit]]
comment = "Above FF P Sector"
text = "660\r\n295"
position = ["N047.41.34.328", "E001.58.11.473"]
size = 40
controller_me = "BB"
default = true
controller_others=[]

[[sector_vertical_limit]]
#comment = "Above FF P Sector"
text = "660\r\n295"
position = ["N047.41.34.328", "E001.58.11.473"]
size = 40
controller_me = "BBN"
controller_others=[]
default = true

[[sector_vertical_limit]]
comment= "FIR sector N"
text = "195\r\n000"
position = ["N046.35.52.994","E000.46.14.289"]
size = 50
controller_me = "BB"
controller_others = ["BBN"]

[[sector_vertical_limit]]
comment= "FIR sector S"
text = "195\r\n000"
position = ["N043.58.43.713","E000.38.44.749"]
size = 50
controller_me = "BB"
controller_others = ["BBS"]

[[sector_vertical_limit]]
comment= "BBN"
text = "660\r\n195"
position = ["N046.35.52.994","E000.46.14.289"]
size = 50
controller_me = "BBN"
controller_others = []
default = true

[[sector_vertical_limit]]
comment= "BBS"
text = "660\r\n195"
position = ["N043.58.43.713","E000.38.44.749"]
size = 50
controller_me = "BBS"
controller_others = []
default = true

[[sector_vertical_limit]]
comment= "BB N but not S"
text = "660\r\n000"
position = ["N043.58.43.713","E000.38.44.749"]
size = 50
controller_me = "BB"
controller_others = ["BBN"]
controller_not_others = ["BBS"]

[[sector_vertical_limit]]
comment= "BB S but not N"
text = "660\r\n000"
position = ["N046.35.52.994","E000.46.14.289"]
size = 50
controller_me = "BB"
controller_others = ["BBS"]
controller_not_others = ["BBN"]
